### ISSUE TITLE
Help messages are different from documentation

### ISSUE THREAD

**Issue by pdharma** [kamaln7/klein#15]
The latest version prints different help messages from those shown in the document
```
$ ./klein --help
Usage of ./klein:
  -key string
    	upload API Key
  -length int
    	code length (default 3)
  -listenAddr string
    	listen address (default "127.0.0.1:5556")
  -path string
    	path to urls (default "/srv/www/urls/")
  -root string
    	root redirect
  -template string
    	path to error template
  -url string
    	path to public facing url (default "http://127.0.0.1:5556/")
```

In addition, the following option does not seem to work:

```
./klein --auth key --auth.key foo
flag provided but not defined: -auth
```

**Comment by kamaln7** [comment]
Oh, sorry about that. I need to release the latest git version as a binary. For the version you've got this should work:

```
./klein -key foo
```

Also, curious to know how you found out about klein 😃

**Comment by kamaln7** [comment]
Hey @pdharma, the latest build is now up on the releases page: https://github.com/kamaln7/klein/releases
